apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  accessPolicy:
    outbound:
      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}
      rules: 
        - application: tokendings
          namespace: {{namespace}}
        - application: api-dings
          cluster: dev-fss
          namespace: {{namespace}}
  port: 3000
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isready
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  tokenx:
    enabled: true
  idporten:
    enabled: true
    redirectURIs:
      - {{redirectUri}}
    postLogoutRedirectURIs:
      - "https://www.nav.no"
    refreshTokenLifetime: 3600

  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}

  env:
    - name: REDIRECT_URI
      value: {{redirectUri}}
  {{#each env}}
    - name: "{{@key}}"
      value: "{{this}}"
  {{/each}}
